# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: GoReleaser

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to build (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout tag (manual run)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ inputs.tag }}
          path: tag
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: "10"
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: 'pnpm'
          cache-dependency-path: 'website/pnpm-lock.yaml'
          
      - name: Install frontend dependencies
        run: pnpm install --dir website
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
        id: setup-go
          
      - name: Run GoReleaser (manual dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: goreleaser/goreleaser-action@v6.3.0
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean --config ../.goreleaser.yaml
          workdir: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOVERSION: ${{ steps.setup-go.outputs.go-version }}

      - name: Run GoReleaser
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: goreleaser/goreleaser-action@v6.3.0
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOVERSION: ${{ steps.setup-go.outputs.go-version }}

      - name: Attest Build Provenance (manual dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/attest-build-provenance@v2.0.0
        with:
          subject-path: 'tag/dist/checksums.txt'

      - name: Attest Build Provenance
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/attest-build-provenance@v2.0.0
        with:
          subject-path: 'dist/checksums.txt'
